[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "exceldatabase"
version = "0.1.0"
description = "A simple Excel-based database system using openpyxl."
authors = [
    { name = "whitespaca", email = "whitespaca@outlook.com" }
]
license = { file = "LICENSE" }
dependencies = [
    "openpyxl"
]
requires-python = ">=3.7"
readme = "README.md"

[tool.setuptools]
packages = ["exceldatabase"]